### ISSUE TITLE
Wrapping Redux connect() with withRouter() confuses WDYR

### ISSUE THREAD

**Issue by MaffooBristol** [welldone-software/why-did-you-render#121]
As per title, not really sure what else I can add!

`export default withRouter(connect(mapStateToProps)(_NotificationBar));`

```
whyDidYouRender error. Please file a bug at https://github.com/welldone-software/why-did-you-render/issues. 
{errorInfo: {…}}
errorInfo:
WDYRPatchedComponent: null
componentNameOrComponent: ƒ C(props)
displayName: "withRouter(Connect(_NotificationBar))"
error: TypeError: Cannot read property 'prototype' of undefined at mn 
(http://localhost:7979/business.f5e0eaa5.js:45079:27658) at e 
(http://localhost:7979/business.f5e0eaa5.js:45079:32377) at Un 
(http://localhost:7979/business.f5e0eaa5.js:45079:32627) at $n 
(http://localhost:7979/business.f5e0eaa5.js:45079:32976) at Object.Vn.e.createElement 
(http://localhost:7979/business.f5e0eaa5.js:45079:34253) at AuthedLayout 
(http://localhost:7979/AuthedLayout.dd37237b.js:2517:85) at renderWithHooks 
(http://localhost:7979/business.f5e0eaa5.js:29330:22) at updateFunctionComponent 
(http://localhost:7979/business.f5e0eaa5.js:31509:24) at mountLazyComponent 
(http://localhost:7979/business.f5e0eaa5.js:31817:21) at beginWork 
(http://localhost:7979/business.f5e0eaa5.js:33026:20)
isShouldTrack: true
options: {include: null, exclude: null, onlyLogs: false, notifier: ƒ, consoleLog: ƒ, …}
rest: [null]
__proto__: Object
__proto__: Object
```

```
/* eslint-disable global-require */
import React from 'react';

export default () => {
  if (process.env.NODE_ENV === 'development') {
    const whyDidYouRender = require('@welldone-software/why-did-you-render');
    whyDidYouRender(React, {
      trackAllPureComponents: true,
      logOwnerReasons: true,
    });
  }
};
```

**Comment by vzaidman** [comment]
Hey!
I added [tests](https://github.com/welldone-software/why-did-you-render/blob/master/tests/librariesTests/react-router-dom.test.js) to see if the library is compatible with `react-router`, including where it's combined with `react-redux`. It seems to me it works. (I also use these in my project)

It seems to me I need more information to understand what goes wrong here.
1. please ensure all the versions of the mentioned libraries (`React`, `react-redux`, `react-router-dom`, and `why-did-you-render`) are updated to the latest one.
2. please use an unminified version of why did you render:
```
const whyDidYouRender = require('@welldone-software/why-did-you-render/dist/cjs/whyDidYouRender.js');
```

**Comment by MaffooBristol** [comment]
Thanks for the response! Everything is latest version. With the the unminified version it now says:
```
"TypeError: Cannot read property 'prototype' of undefined
    at isReactClassComponent (http://localhost:7979/business.f5e0eaa5.js:18331:20)
    at patchMemoComponent (http://localhost:7979/business.f5e0eaa5.js:18499:45)
    at createPatchedComponent (http://localhost:7979/business.f5e0eaa5.js:18602:12)
    at getPatchedComponent (http://localhost:7979/business.f5e0eaa5.js:18621:30)
    at Object.React.createElement (http://localhost:7979/business.f5e0eaa5.js:18679:32)
    at AuthedLayout (http://localhost:7979/AuthedLayout.dd37237b.js:2866:20)
    at renderWithHooks (http://localhost:7979/business.f5e0eaa5.js:34828:22)
    at updateFunctionComponent (http://localhost:7979/business.f5e0eaa5.js:37007:24)
    at mountLazyComponent (http://localhost:7979/business.f5e0eaa5.js:37315:21)
    at beginWork (http://localhost:7979/business.f5e0eaa5.js:38524:20)"
```

WYDR is installed correctly I believe- it's been working perfectly fine except for when wrapping the withRouter.

It is using lazyLoad, that might explain it:

**The router:**
```
const routes = {
  AuthedLayout: import('../layouts/AuthedLayout'),
};
<Route path="/application/:id" component={lazyLoad(routes.AuthedLayout, 400)} />
```

**lazyLoad.jsx**
```
/* eslint-disable react/jsx-props-no-spreading */
import React, { lazy, Suspense } from 'react';

import Loading from '/shared/components/Loading';

export default (route, timeout = 800, isWrapped) => {
  const Component = lazy(() => {
    if (!timeout) {
      return route;
    }
    return Promise.all([
      route,
      new Promise((resolve) => setTimeout(resolve, timeout)),
    ]).then(([moduleExports]) => moduleExports);
  });
  return (props) => (
    <Suspense fallback={<Loading isWrapped={isWrapped} />}>
      <Component {...props} />
    </Suspense>
  );
};
```

**Comment by MaffooBristol** [comment]
Ps. I'm using parcel.js as my package manager, which supports `import()` style module loading

**Comment by vzaidman** [comment]
try version 4.2.3 that i just released

**Comment by MaffooBristol** [comment]
@vzaidman 
Thanks Vitali, unfortunately it's still doing it, same error:

```
"TypeError: Cannot read property 'prototype' of undefined
    at isReactClassComponent (http://localhost:7979/business.f5e0eaa5.js:18348:20)
    at patchMemoComponent (http://localhost:7979/business.f5e0eaa5.js:18516:45)
    at createPatchedComponent (http://localhost:7979/business.f5e0eaa5.js:18627:12)
    at getPatchedComponent (http://localhost:7979/business.f5e0eaa5.js:18646:30)
    at Object.React.createElement (http://localhost:7979/business.f5e0eaa5.js:18722:32)
    at AuthedLayout (http://localhost:7979/AuthedLayout.dd37237b.js:2868:20)
    at renderWithHooks (http://localhost:7979/business.f5e0eaa5.js:34871:22)
    at updateFunctionComponent (http://localhost:7979/business.f5e0eaa5.js:37050:24)
    at mountLazyComponent (http://localhost:7979/business.f5e0eaa5.js:37358:21)
    at beginWork (http://localhost:7979/business.f5e0eaa5.js:38567:20)"
```

If there's something I could hack about with in the whyDidYouRender.js file locally to test then please let me know. Thanks!

**Comment by MaffooBristol** [comment]
Inside `function createPatchedComponent() {}` I added `console.log(Component);`

It seems to shout at me when the component is a function rather than a React component object? I'm not sure of the internals of how it works...! 

![image](https://user-images.githubusercontent.com/3296828/83330577-cb1a3b00-a287-11ea-993a-1e94fec077e2.png)

**Comment by vzaidman** [comment]
Are you sure your code works when WDYR is disabled?

**Comment by MaffooBristol** [comment]
My code works fine either way, it just shows this warning

**Comment by vzaidman** [comment]
It's very unclear to me! looks like more info is needed.
does the error appear when you switch the dynamic import to be a regular one?

**Comment by MaffooBristol** [comment]
Thanks- just tried it with a regular import and it still does it 🤷‍♂️

**Comment by vzaidman** [comment]
are you sure
```
console.log(Component);
```
never returns `null`?

**Comment by vzaidman** [comment]
also- please make sure you have the latest version 4.2.4 of WDYR

**Comment by MaffooBristol** [comment]
Yes it's never null. The `withRouter()` wrapped components creating the warning are `typeof function` whilst the other ones are `typeof object`

Definitely v4.2.4 as I've checked for the lines that were added in earlier today

**Comment by vzaidman** [comment]
and what type is `_NotificationBar` ?

**Comment by MaffooBristol** [comment]
Very stripped down version:

```
import React from 'react';
import { connect } from 'react-redux';
import { withRouter } from 'react-router-dom';

function _NotificationBar({ dispatch }) {
  return <>Foo</>;
}

const mapStateToProps = (state, ownProps) => ({
  // ...
});

export default withRouter(connect(mapStateToProps)(_NotificationBar));
```

**Comment by vzaidman** [comment]
please paste the error stack trace again

**Comment by vzaidman** [comment]
I mean error stack trace when you remove the lazy thingie

**Comment by MaffooBristol** [comment]
It appears to be identical minus the `mountLazyComponent`

```
error: TypeError: Cannot read property 'prototype' of undefined at isReactClassComponent 
(http://localhost:7979/business.f5e0eaa5.js:18348:20) at patchMemoComponent 
(http://localhost:7979/business.f5e0eaa5.js:18516:45) at createPatchedComponent 
(http://localhost:7979/business.f5e0eaa5.js:18628:12) at getPatchedComponent 
(http://localhost:7979/business.f5e0eaa5.js:18647:30) at Object.React.createElement 
(http://localhost:7979/business.f5e0eaa5.js:18723:32) at AuthedLayout 
(http://localhost:7979/business.f5e0eaa5.js:80457:20) at renderWithHooks 
(http://localhost:7979/business.f5e0eaa5.js:34872:22) at updateFunctionComponent 
(http://localhost:7979/business.f5e0eaa5.js:37051:24) at beginWork 
(http://localhost:7979/business.f5e0eaa5.js:38576:20) at beginWork$1 
(http://localhost:7979/business.f5e0eaa5.js:43104:18)
```

**Comment by MaffooBristol** [comment]
```
function isReactClassComponent(Component) {
  console.log(Component);
  return Component.prototype && !!Component.prototype.isReactComponent;
}
```
returns `undefined` 🤔

**Comment by vzaidman** [comment]
can you please check how come this component passes passes further in the `getIsSupportedComponentType` function in the library?

**Comment by MaffooBristol** [comment]
Yeah the problem components (as `Comp`) are coming through as functions, but then many of the working ones are also functions- so it will return true in `getIsSupportedComponentType`

However other working ones have their named component in the logs, like
```
AuthedLayout() {
  return (
    /*#__PURE__*/
    _react.default.createElement(_react.default.Fragment, null,
    /*#__PURE__*/
    _react.default.createElement(_NotificationBar.default, null),
    /…
```
 but the problem ones are like
```
C(props) {
    var wrappedComponentRef = props.wrappedComponentRef,
        remainingProps = (0, _objectWithoutPropertiesLoose2.default)(props, ["wrappedComponentRef"]);
    return _react.default.cre…
```

Anything else I can log and check?

**Comment by vzaidman** [comment]
I don't understand how come they are functions in "getIsSupportedComponentType" (which let's them into the WDYR logic) and then undefined in (isReactClassComponent) :0

**Comment by vzaidman** [comment]
try `4.2.5` please! i had an idea

**Comment by MaffooBristol** [comment]
@vzaidman Success! It works 😀

Thanks so much for looking into this, I really appreciate the time and effort you've put in.

**Comment by vzaidman** [comment]
@MaffooBristol Great!
I appreciate your help in solving this issue!

**Comment by MaffooBristol** [comment]
No problem, glad to help 🙂
