### ISSUE TITLE
whyDidYouRender error

### ISSUE THREAD

**Issue by hayden-liao** [welldone-software/why-did-you-render#234]
console.log
    whyDidYouRender error. Please file a bug at https://github.com/welldone-software/why-did-you-render/issues. {
      errorInfo: {
        error: TypeError: Cannot read properties of undefined (reading '$$typeof')
            at isMemoComponent (/home/hliao/dev/crab2/webserver/node_modules/@welldone-software/why-did-you-render/src/utils.js:24:20)
            at Object.e.createElement (/home/hliao/dev/crab2/webserver/node_modules/@welldone-software/why-did-you-render/src/whyDidYouRender.js:105:11)
            at HoverTooltipUnwrapped (/home/hliao/dev/crab2/webserver/app/src/hybrid/core/HoverTooltip.atom.tsx:38:19)
            at renderWithHooks (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:14985:18)
            at mountIndeterminateComponent (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:17811:13)
            at beginWork (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:19049:16)
            at beginWork$1 (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:23940:14)
            at performUnitOfWork (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:22779:12)
            at workLoopSync (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:22707:5)
            at renderRootSync (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:22670:7)
            at performSyncWorkOnRoot (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:22293:18)
            at scheduleUpdateOnFiber (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:21881:7)
            at updateContainer (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:25482:3)
            at /home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:26021:7
            at unbatchedUpdates (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:22431:12)
            at legacyRenderSubtreeIntoContainer (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:26020:5)
            at Object.render (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:26103:10)
            at /home/hliao/dev/crab2/webserver/node_modules/@testing-library/react/dist/pure.js:101:25
            at batchedUpdates$1 (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom.development.js:22380:12)
            at act (/home/hliao/dev/crab2/webserver/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
            at render (/home/hliao/dev/crab2/webserver/node_modules/@testing-library/react/dist/pure.js:97:26)
            at renderContent (/home/hliao/dev/crab2/webserver/app/src/hybrid/annotation/ckEditorPlugins/components/test/RefreshingContent.molecule.test.tsx:90:31)
            at renderAndLoad (/home/hliao/dev/crab2/webserver/app/src/hybrid/annotation/ckEditorPlugins/components/test/RefreshingContent.molecule.test.tsx:99:23)
            at Object.<anonymous> (/home/hliao/dev/crab2/webserver/app/src/hybrid/annotation/ckEditorPlugins/components/test/RefreshingContent.molecule.test.tsx:319:37)
            at Object.asyncJestTest (/home/hliao/dev/crab2/webserver/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:173:37)
            at /home/hliao/dev/crab2/webserver/node_modules/jest-jasmine2/build/queueRunner.js:89:12
            at new Promise (<anonymous>)
            at mapper (/home/hliao/dev/crab2/webserver/node_modules/jest-jasmine2/build/queueRunner.js:72:19)
            at /home/hliao/dev/crab2/webserver/node_modules/jest-jasmine2/build/queueRunner.js:119:41,
        componentNameOrComponent: undefined,
        rest: [
          [Object],
          'REPORT.CONFIG.ASSET_SELECTION_WARNING_TOOLTIP_EXPAND'
        ],
        options: {
          include: null,
          exclude: null,
          notifier: [Function: defaultNotifier],
          onlyLogs: false,
          consoleLog: [Function: log],
          consoleGroup: [Function: group],
          consoleGroupEnd: [Function: groupEnd],
          logOnDifferentValues: false,
          trackHooks: true,
          titleColor: '#058',
          diffNameColor: 'blue',
          diffPathColor: 'red',
          trackAllPureComponents: true
        },
        isShouldTrack: null,
        displayName: null,
        WDYRPatchedComponent: null
      }
    }

      at Object.e.createElement (node_modules/@welldone-software/why-did-you-render/src/whyDidYouRender.js:124:15)

**Comment by vzaidman** [comment]
Hey! Give us a little more information.
What component fails? Is it special? Some sort of library component maybe?

**Comment by vzaidman** [comment]
You are free to re-open the issue with more info provided
