### ISSUE TITLE
Doesn't work with class components wrapped in React.memo 

### ISSUE THREAD

**Issue by Hypnosphi** [welldone-software/why-did-you-render#50]
See https://github.com/welldone-software/why-did-you-render/issues/10#issuecomment-480961161

**Comment by Hypnosphi** [comment]
It throws following exception:

```
TypeError: Cannot set property 'props' of undefined
    at Component (http://localhost:6006/vendors~main.317c2c034316233265a1.bundle.js:267013:14)
    at WithState (http://localhost:6006/vendors~main.317c2c034316233265a1.bundle.js:269148:33)
    at WDYRWrappedByMemoFunctionalComponent (http://localhost:6006/vendors~main.317c2c034316233265a1.bundle.js:83010:12)
    at renderWithHooks (http://localhost:6006/vendors~main.317c2c034316233265a1.bundle.js:233595:18)
    at updateFunctionComponent (http://localhost:6006/vendors~main.317c2c034316233265a1.bundle.js:235284:20)
    at updateSimpleMemoComponent (http://localhost:6006/vendors~main.317c2c034316233265a1.bundle.js:235230:10)
    at updateMemoComponent (http://localhost:6006/vendors~main.317c2c034316233265a1.bundle.js:235149:14)
    at beginWork (http://localhost:6006/vendors~main.317c2c034316233265a1.bundle.js:236346:16)
    at performUnitOfWork (http://localhost:6006/vendors~main.317c2c034316233265a1.bundle.js:239969:12)
    at workLoop (http://localhost:6006/vendors~main.317c2c034316233265a1.bundle.js:240009:24)
```

The reason is that `WDYRWrappedByMemoFunctionalComponent` calls the component as a function while in fact it is a class

**Comment by vzaidman** [comment]
ok i might indeed fix it. and maybe even soon but React.memo is made for functional components:
https://reactjs.org/docs/react-api.html#reactmemo

are you sure it even makes your class component pure?

**Comment by Hypnosphi** [comment]
Yeah I'm pretty sure: https://github.com/facebook/react/blob/master/packages/react-reconciler/src/__tests__/ReactMemo-test.internal.js#L222

**Comment by vzaidman** [comment]
added a prove that this happens (a test that fails) to the following branch:
https://github.com/welldone-software/why-did-you-render/tree/%2350-memo-a-class-component

Looks like a not too hard thing to fix, if anybody wants to try to do it.

**Comment by vzaidman** [comment]
fixed in https://github.com/welldone-software/why-did-you-render/tree/v3.3.4

**Comment by georgiosd** [comment]
@vzaidman I'm having the same problem with a functional component - when it's memo'd... it's with NextJS, not sure if it matters. Shall I open a new issue?
